### ISSUE TITLE
Favorites - Categories

### ISSUE THREAD

**Issue by ghost** [Catgrills/Exhentai.usercss#2]
There is a problem with Categories under Favorites, the counter is overlapping. Look at the screenshot.

![screenshot from 2018-08-05 21-03-43](https://user-images.githubusercontent.com/8683793/43691468-6e4af7ce-98f3-11e8-9bc7-3ebf544905e7.png)

**Comment by Catgrills** [comment]
I see, I didn't notice it since I changed the Favorites label, you can change the font-size of the following element (you can set it below 18pt if the issue persists) : 

``` css
div[style="float:left; text-align:left; height:20px; padding:2px 0 0 3px"] {
    font-size: 18pt; 
}
``` 

And don't forget to install the font I used.
